(define (make-account balance password)
  (define my-password password)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (dispatch secret m)
    (if (eq? secret my-password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknow request -- MAKE-ACCOUNT" m)))
        (error "Wrong password -- MAKE-ACCOUNT" secret)))
  dispatch)
